### ISSUE TITLE
Update release repository for ROS 2 rolling release support

### ISSUE THREAD

**Issue by nuclearsandwich** [ubuntu-robotics/ament_nodl#4]
In order to be automatically released from Foxy to Rolling, and in order automatically release from Rolling to future distributions, the rolling release automation needs to be able to push to release repositories.
For this reason, [REP 2002](https://www.ros.org/reps/rep-2002.html#managing-build-farm-writable-release-repositories) specified that release repositories for the Rolling distribution would be created in the [ros2-gbp](https://github.com/ros2-gbp) organization if they were not part of that organization already.

When the Rolling distribution was created, a new release repository for ament_nodl, was created at https://github.com/ros2-gbp/ament_nodl-release

My recommendation would be for the ament_nodl team to switch to using the ros2-gbp release repository for all ROS 2 releases of ament_nodl.
With your confirmation, I can add maintainers to the repository in ros2-gbp with full administrative access. Then we would only need to update the release repository entry in other distros where ament_nodl is released, which I believe is just Foxy.

Once maintainership is configured, I would suggest archiving the previous release repository keeping it intact for any sources still using it for earlier releases.

**Comment by kyrofa** [comment]
Hey @nuclearsandwich, sure that's fine. Go ahead and add me, I'll add the other folks.

**Comment by nuclearsandwich** [comment]
Thanks, I've added you to a team with admin rights on ament_nodl-release and nodl-release. I'm not sure whether you are able to add new members to the organization which is a prerequisite to adding them to the team. If not, let me know and we'll figure out how to coordinate.

**Comment by kyrofa** [comment]
> Then we would only need to update the release repository entry in other distros where ament_nodl is released, which I believe is just Foxy.

@nuclearsandwich it looks like the old ones are [still in rosdistro for Foxy](https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml#L1389), were you going to update those, or are you wanting us to?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich it looks like the old ones are [still in rosdistro for Foxy](https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml?rgh-link-date=2020-08-13T17%3A32%3A15Z#L1389), were you going to update those, or are you wanting us to?

Looks like it was done in https://github.com/ros/rosdistro/pull/26221

**Comment by kyrofa** [comment]
Oh right, yeah, let me close this.
